[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
marketplace = "2x2hWcMfrsfkRbh3aXWFV5BEoa4p6e2uUamVnkHEt8Wx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
